try{
    harry
}catch(error){
    console.log("This is the name of the error "+error.name)
    console.log("This is the error message "+error.message)
}